services:
  webserver:
    image: myownimage
    build:
      context: ./
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
     - ./index.html:/usr/share/nginx/html/index.html:ro
    environment:
      SECRET_KEY: ${SECRET_KEY:-dummySecret}
    env_file: .env


# docker run -p "8080:80" -e SECRET_KEY=dummySecret -v ./index.html:/usr/share/nginx/html/index.html:r myownimage
